Update the PATH environment variable to be able to run solidity tests…
EspressoSystems/espresso-sequencer pull request #2395
Opened 2024-12-12 21:04 UTC by philippecamacho

I made this PR because I was not able to run the solidity tests using nix. The problem was that the diff-test executable was not in the PATH environment variable.

### This PR:
Update the `PATH` environment variable in flake.nix so that the diff-test executable can be found.

### Key places to review:
`flake.nix` file.

2024-12-12 22:24 UTC, alysiahuggins approved these changes

2024-12-13 08:07 UTC, sveitser commented
I think we should avoid this because it leads to cases where one may compile with "release" expecting to run these binaries but due to PATH settings one will still run the debug binaries. 

I think we don't need to compile diff test with release or is it too slow? We now have some optimizations for the "test" profile too and I think it should be fine?

2024-12-13 08:10 UTC, sveitser requested changes
See other comment

2024-12-13 08:30 UTC, sveitser commented
I think we can change the just file recipes to build the diff test binary to `cargo build --profile test --bin diff-test`

2024-12-13 13:09 UTC, sveitser approved these changes

2024-12-13 13:26 UTC, merged